// auth types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

// alert types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//RDPS types
export const FETCH_RDPSDATA = "FETCH_RDPSDATA"
export const GET_RDP = "GET_RDP"
export const FETCH_RDPSSELECTOPTIONS = "FETCH_RDPSSELECTOPTIONS"
export const ADD_RDPSDATA = "ADD_RDPSDATA"
export const EDIT_RDPSDATA = "EDIT_RDPSDATA"

//VPS types
export const FETCH_VPSDATA = "FETCH_VPSDATA"
export const GET_VPS = "GET_VPS"
export const FETCH_VPSSELECTOPTIONS = "FETCH_VPSSELECTOPTIONS"
export const ADD_VPSDATA = "ADD_VPSDATA"
export const EDIT_VPSDATA = "EDIT_VPSDATA"

//CPANEL types
export const FETCH_CPANELDATA = "FETCH_CPANELDATA"
export const GET_CPANEL = "GET_CPANEL"
export const FETCH_CPANELSELECTOPTIONS = "FETCH_CPANELSELECTOPTIONS"
export const ADD_CPANELDATA = "ADD_CPANELDATA"
export const EDIT_CPANELDATA = "EDIT_CPANELDATA"

//App types
export const APP_LOADING = "APP_LOADING"
export const APP_LOADING_END = "APP_LOADING_END"

// User types
export const FETCH_USERS = 'FETCH_USERS';
export const USER_CHANGE_STATUS = 'USER_CHANGE_STATUS';
export const RESET_PASSWORD = 'RESET_PASSWORD';
