export const tableColumns = [
  {
    name: "Country",
    selector: (row) => row["country"],
    sortable: false,
    center: false,
    width: "7%",
  },
  {
    name: "IP",
    selector: (row) => `${row.ip}`,
    sortable: false,
    center: false,
    width: "10%",
  },
  {
    name: "Windows",
    selector: (row) => `${row.windows}`,
    sortable: false,
    center: false,
    width: "10%",
  },
  {
    name: "RAM",
    selector: (row) => `${row.ram}`,
    sortable: false,
    center: false,
    width: "10%",
  },
  {
    name: "Access",
    selector: (row) => row.access,
    sortable: false,
    center: false,
    width: "7%",
  },
  {
    name: "User",
    selector: (row) => `${row.user}`,
    sortable: false,
    center: false,
    width: "10%",
  },
  {
    name: "Detect Hosting",
    selector: (row) => row.detect_hosting,
    sortable: false,
    center: false,
    width: "10%",
  },
  {
    name: "Seller",
    selector: (row) => row.seller,
    sortable: false,
    center: false,
    width: "10%",
  },
  {
    name: "Price",
    selector: (row) => row.price,
    sortable: false,
    center: false,
    width: "6%",
  },
  {
    name: "Added on",
    selector: (row) => row.added_on,
    sortable: false,
    center: false,
    width: "12%",
  },
  {
    name: "Action",
    selector: (row) => row["action"],
    sortable: false,
    center: true,
    width: "8%",
  },
];